server:
  port: 8080

spring:
  sql:
    init:
#      schema-locations: classpath:db/quartz_tables_h2.sql
      mode: always
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:./devdb
    driverClassName: org.h2.Driver


logging:
  level:
    org:
      hibernate:
        sql: debug






